In [1]:
import numpy as np

In [2]:
ab=[2,3,4,5,6,7]
print(ab)
print(type(ab))

[2, 3, 4, 5, 6, 7]
<class 'list'>


In [3]:
a=np.array([1,2,3,4,5,6])
print(a)
print(type(a))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [4]:
a=np.array([1,2,3,4,5,6])
print(a)
print(type(a))
print(a.dtype)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
int32


In [5]:
a=np.array([1,2.2,3,4,5,6])
print(a)
print(type(a))
print(a.dtype)

[1.  2.2 3.  4.  5.  6. ]
<class 'numpy.ndarray'>
float64


In [6]:
a=np.array([1,"2",3,4,5,6])
print(a)
print(type(a))
print(a.dtype)

['1' '2' '3' '4' '5' '6']
<class 'numpy.ndarray'>
<U11


In [7]:
# Working With Dimensional Array

In [9]:
# 1 d array
import numpy
a=numpy.array([1,2,3,4,5,6])
print(a.ndim)


1


In [10]:
# 0 D array
a=np.array(12)
print(a.ndim)

0


In [11]:
# 2 D array
a=np.array([[12],[12]])
print(a.ndim)


2


In [12]:
# 2 D array
a=np.array([[12,11,22,12],[12,11,22,12]])
print(a.shape)
print(a)
print(a.ndim)
print(a.dtype)
print(type(a))

(2, 4)
[[12 11 22 12]
 [12 11 22 12]]
2
int32
<class 'numpy.ndarray'>


In [13]:
# 3 D array
a=np.array([[[12,11,22,12],[12,11,22,12]],[[12,11,22,12],[12,11,22,12]]])
print(a.shape)

print(a.ndim)
print(a)

(2, 2, 4)
3
[[[12 11 22 12]
  [12 11 22 12]]

 [[12 11 22 12]
  [12 11 22 12]]]


In [14]:
# 4 D array
a=np.array([[[[12,11,22,12],[12,11,22,12]],[[12,11,22,12],[12,11,22,12]],[[12,11,22,12],[12,11,22,12]],[[12,11,22,12],[12,11,22,12]]]])
print(a.shape)

print(a.ndim)
print(a)

(1, 4, 2, 4)
4
[[[[12 11 22 12]
   [12 11 22 12]]

  [[12 11 22 12]
   [12 11 22 12]]

  [[12 11 22 12]
   [12 11 22 12]]

  [[12 11 22 12]
   [12 11 22 12]]]]


In [15]:
## working with Reshape


In [16]:
# 1 D array
a=np.array([1,2,3,4,5,6,7,8,9,10])
ab=a.reshape(5,2)
print(ab.ndim)
ab

2


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [17]:
# 1 D array
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
ab=a.reshape(2,2,3)
print(ab.ndim)
ab

3


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [18]:
# Array Split
# sort
# concate
# filter
# Where




a=np.array([11,22,32,24,25,6,27,82,29,120,1])
ab=np.sort(a)
ab

array([  1,   6,  11,  22,  24,  25,  27,  29,  32,  82, 120])

In [19]:
a=np.array([11,22,32,24,25,6,27,82,29,120,1])
ab=-np.sort(-a)
ab


array([120,  82,  32,  29,  27,  25,  24,  22,  11,   6,   1])

In [20]:
a=np.array([11,22,32,24,25,6,27,82,29,120,1,66])
ab=np.array_split(a,6)
ab

[array([11, 22]),
 array([32, 24]),
 array([25,  6]),
 array([27, 82]),
 array([ 29, 120]),
 array([ 1, 66])]

In [21]:
# Working filter

a=np.array([2,3,5])
ab=np.array([True,False,False])
ab1=a[ab]
ab1
    

array([2])